nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Controllers/EmailAccountController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Messages;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Messages;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class EmailAccountController : BaseAdminController
    {
        #region Fields

        private readonly EmailAccountSettings _emailAccountSettings;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IEmailAccountModelFactory _emailAccountModelFactory;
        private readonly IEmailAccountService _emailAccountService;
        private readonly IEmailSender _emailSender;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public EmailAccountController(EmailAccountSettings emailAccountSettings,
            ICustomerActivityService customerActivityService,
            IEmailAccountModelFactory emailAccountModelFactory,
            IEmailAccountService emailAccountService,
            IEmailSender emailSender,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IGenericAttributeService genericAttributeService,
            IWorkContext workContext,
            IStoreContext storeContext)
        {
            _emailAccountSettings = emailAccountSettings;
            _customerActivityService = customerActivityService;
            _emailAccountModelFactory = emailAccountModelFactory;
            _emailAccountService = emailAccountService;
            _emailSender = emailSender;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _genericAttributeService = genericAttributeService;
            _workContext = workContext;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> List(bool showtour = false)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            //prepare model
            var model = await _emailAccountModelFactory.PrepareEmailAccountSearchModelAsync(new EmailAccountSearchModel());

            //show configuration tour
            if (showtour)
            {
                var hideCard = await _genericAttributeService.GetAttributeAsync<bool>(await _workContext.GetCurrentCustomerAsync(), NopCustomerDefaults.HideConfigurationStepsAttribute);

                var closeCard = await _genericAttributeService.GetAttributeAsync<bool>(await _workContext.GetCurrentCustomerAsync(), NopCustomerDefaults.CloseConfigurationStepsAttribute);

                if (!hideCard && !closeCard)
                    ViewBag.ShowTour = true;
            }

            return View(model);
        }

        [HttpPost]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> List(EmailAccountSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return await AccessDeniedDataTablesJson();

            //prepare model
            var model = await _emailAccountModelFactory.PrepareEmailAccountListModelAsync(searchModel);

            return Json(model);
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> MarkAsDefaultEmail(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            var defaultEmailAccount = await _emailAccountService.GetEmailAccountByIdAsync(id);
            if (defaultEmailAccount == null)
                return RedirectToAction("List");

            _emailAccountSettings.DefaultEmailAccountId = defaultEmailAccount.Id;
            await _settingService.SaveSettingAsync(_emailAccountSettings);

            return RedirectToAction("List");
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            //prepare model
            var model = await _emailAccountModelFactory.PrepareEmailAccountModelAsync(new EmailAccountModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> Create(EmailAccountModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var emailAccount = model.ToEntity<EmailAccount>();

                //set password manually
                emailAccount.Password = model.Password;
                await _emailAccountService.InsertEmailAccountAsync(emailAccount);

                //activity log
                await _customerActivityService.InsertActivityAsync("AddNewEmailAccount",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewEmailAccount"), emailAccount.Id), emailAccount);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Configuration.EmailAccounts.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = emailAccount.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = await _emailAccountModelFactory.PrepareEmailAccountModelAsync(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> Edit(int id, bool showtour = false)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            //try to get an email account with the specified id
            var emailAccount = await _emailAccountService.GetEmailAccountByIdAsync(id);
            if (emailAccount == null)
                return RedirectToAction("List");

            //prepare model
            var model = await _emailAccountModelFactory.PrepareEmailAccountModelAsync(null, emailAccount);

            //show configuration tour
            if (showtour)
            {
                var hideCard = await _genericAttributeService.GetAttributeAsync<bool>(await _workContext.GetCurrentCustomerAsync(), NopCustomerDefaults.HideConfigurationStepsAttribute);

                var closeCard = await _genericAttributeService.GetAttributeAsync<bool>(await _workContext.GetCurrentCustomerAsync(), NopCustomerDefaults.CloseConfigurationStepsAttribute);

                if (!hideCard && !closeCard)
                    ViewBag.ShowTour = true;
            }

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task<IActionResult> Edit(EmailAccountModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageEmailAccounts))
                return AccessDeniedView();

            //try to get an email account with the specified id
            var emailAccount = await _emailAccountService.GetEmailAccountByIdAsync(model.Id);
            if (emailAccount == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                emailAccount = model.ToEntity(emailAccount);
                await _emailAccountService.UpdateEmailAccountAsync(emailAccount);

                //activity log
                await _customerActivityService.InsertActivityAsync("EditEmailAccount",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditEmailAccount"), emailAccount.Id), emailAccount);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Configuration.EmailAccounts.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = emailAccount.Id }) : RedirectToAction("List");
            }

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/EmailAccount/Create.cshtml
@model EmailAccountModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.EmailAccounts.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Email accounts");
}

<form asp-controller="EmailAccount" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.EmailAccounts.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Configuration.EmailAccounts.BackToList")</a>                
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.EmailAccountDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/EmailAccount/Edit.cshtml
@model EmailAccountModel
@using Nop.Web.Framework.Models.AdminAreaTour

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.EmailAccounts.EditEmailAccountDetails").Text;
    //tour step
    ViewBag.TourStep = TourStep.EmailAccount;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Email accounts");
}

@await Html.PartialAsync("_AdminTour")

<form asp-controller="EmailAccount" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.EmailAccounts.EditEmailAccountDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Configuration.EmailAccounts.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="emailAccount-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.EmailAccountDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="emailAccount-delete" />

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/EmailAccount/List.cshtml
@model EmailAccountSearchModel
@inject Nop.Services.Messages.IEmailAccountService emailAccountService
@using Nop.Web.Framework.Models.AdminAreaTour

@{
  //page title
  ViewBag.PageTitle = T("Admin.Configuration.EmailAccounts").Text;
  //tour step
  ViewBag.TourStep = TourStep.EmailAccountList;
  //active menu item (system name)
  Html.SetActiveMenuItemSystemName("Email accounts");

  string editQueryString = string.Empty;
  var showTour = ViewBag.ShowTour ?? false;
  if (showTour)
  {
      editQueryString = "?showtour=true";
  }
}

@await Html.PartialAsync("_AdminTour")

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.Configuration.EmailAccounts")
    </h1>
    <div class="float-right">
        <a asp-action="Create" class="btn btn-primary">
            <i class="fas fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.EmailAccountListButtons })
    </div>
</div>

  <section class="content">
   <div class="container-fluid">
    <div class="form-horizontal">
        <div class="cards-group">
            <div class="card card-default">
                <div class="card-body">
                    <div id="email-accounts-area">
                        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.EmailAccounts", Docs.EmailAccounts + Utm.OnAdmin)" />

                        @await Html.PartialAsync("Table", new DataTablesModel
                        {
                            Name = "email-accounts-grid",
                            RowIdBasedOnField = nameof(EmailAccountModel.Email),
                            UrlRead = new DataUrl("List", "EmailAccount", null),
                            Length = Model.PageSize,
                            LengthMenu = Model.AvailablePageSizes,
                            ColumnCollection = new List<ColumnProperty>
                            {
                                new ColumnProperty(nameof(EmailAccountModel.Email))
                                {
                                    Title = T("Admin.Configuration.EmailAccounts.Fields.Email").Text
                                },
                                new ColumnProperty(nameof(EmailAccountModel.DisplayName))
                                {
                                    Title = T("Admin.Configuration.EmailAccounts.Fields.DisplayName").Text,
                                    Width = "200"
                                },
                                new ColumnProperty(nameof(EmailAccountModel.IsDefaultEmailAccount))
                                {
                                    Title = T("Admin.Configuration.EmailAccounts.Fields.IsDefaultEmailAccount").Text,
                                    Width = "200",
                                    ClassName =  NopColumnClassDefaults.CenterAll,
                                    Render = new RenderBoolean()
                                },
                                new ColumnProperty(nameof(EmailAccountModel.Id))
                                {
                                    Title = T("Admin.Configuration.EmailAccounts.Fields.MarkAsDefaultEmail").Text,
                                    Width = "300",
                                    ClassName =  NopColumnClassDefaults.CenterAll + " column-default",
                                    Render = new RenderButtonCustom(NopButtonClassDefaults.Success, T("Admin.Configuration.EmailAccounts.Fields.MarkAsDefaultEmail").Text)
                                    {
                                        Url = Url.Content("~/Admin/EmailAccount/MarkAsDefaultEmail/")
                                    }
                                },
                                new ColumnProperty(nameof(EmailAccountModel.Id))
                                {
                                    Title = T("Admin.Common.Edit").Text,
                                    Width = "100",
                                    ClassName =  NopColumnClassDefaults.Button + " column-edit",
                                    Render = new RenderCustom("renderColumnEdit")
                                }
                            }
                        })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

<script>
    function renderColumnEdit(data, type, row, meta) {
        return '<a href="@Url.Content("~/Admin/EmailAccount/Edit/")' + data + '@(editQueryString)" class="btn btn-default"><i class="fas fa-pencil-alt"></i>@T("Admin.Common.Edit").Text</a>';
    }
</script>

nopCommerce_4.40.4_Source/Presentation/Nop.Web/Areas/Admin/Views/EmailAccount/_CreateOrUpdate.cshtml
@model EmailAccountModel

<div asp-validation-summary="ModelOnly"></div>
<input asp-for="Id" type="hidden" />

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.EmailAccountDetailsTop, additionalData = Model })
                <div class="card card-default">
                    <div class="card-body">
                        <div class="form-group row" id="email-area">
                            <div class="col-md-3">
                                <nop-label asp-for="Email"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Email" asp-required="true"/>
                                <span asp-validation-for="Email"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="display-name-area">
                            <div class="col-md-3">
                                <nop-label asp-for="DisplayName"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="DisplayName" asp-required="true"/>
                                <span asp-validation-for="DisplayName"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="host-area">
                            <div class="col-md-3">
                                <nop-label asp-for="Host"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Host"/>
                                <span asp-validation-for="Host"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="port-area">
                            <div class="col-md-3">
                                <nop-label asp-for="Port"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Port"/>
                                <span asp-validation-for="Port"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="username-area">
                            <div class="col-md-3">
                                <nop-label asp-for="Username"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="Username"/>
                                <span asp-validation-for="Username"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="password-area">
                            <div class="col-md-3">
                                <nop-label asp-for="Password"/>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">
                                    <nop-editor asp-for="Password" autocomplete="new-password"/>
                                    <div class="input-group-append">
                                        @if (Model.Id > 0)
                                        {
                                            <button type="submit" name="changepassword" class="btn btn-info">
                                                @T("Admin.Configuration.EmailAccounts.Fields.Password.Change")
                                            </button>
                                        }
                                    </div>
                                </div>
                                <span asp-validation-for="Password"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="ssl-area">
                            <div class="col-md-3">
                                <nop-label asp-for="EnableSsl"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="EnableSsl"/>
                                <span asp-validation-for="EnableSsl"></span>
                            </div>
                        </div>
                        <div class="form-group row" id="default-area">
                            <div class="col-md-3">
                                <nop-label asp-for="UseDefaultCredentials"/>
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="UseDefaultCredentials"/>
                                <span asp-validation-for="UseDefaultCredentials"></span>
                            </div>
                        </div>
                    </div>
                </div>
                @if (Model.Id > 0)
                {
                    <div class="card card-default" id="test-email-area">
                        <div class="card-header">
                            @T("Admin.Configuration.EmailAccounts.SendTestEmail")
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="SendTestEmailTo"/>
                                </div>
                                <div class="col-md-9">
                                    <div class="input-group">
                                        <nop-editor asp-for="SendTestEmailTo"/>
                                        <div class="input-group-append">
                                            <button type="submit" name="sendtestemail" class="btn btn-info">
                                                @T("Admin.Configuration.EmailAccounts.SendTestEmail.Button")
                                            </button>
                                        </div>
                                    </div>
                                    <span asp-validation-for="SendTestEmailTo"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.EmailAccountDetailsBottom, additionalData = Model })
            </div>
        </div>
    </div>
</section>